In [1]:
import numpy as np

In [ ]:
"""
Numpy provides a high performance multidimensional array object and tools
"""

In [2]:
# creating a numpy array
# 1 D Array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
# 2 D Array
b = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
"""
Advantages of Numpy over list :
1. Less memory
2. Fast
3. Convenient
"""

In [4]:
import time
import sys
# size of list
List = range(1000)
print(sys.getsizeof(5) * len(List))

28000


In [7]:
# exclude 1000
NPArray = np.arange(1000)
print(NPArray.size * NPArray.itemsize)

8000


In [ ]:
# first point is proved

In [11]:
SIZE = 100000
L1 = range(SIZE)
L2 = range(SIZE)
NA1 = np.arange(SIZE)
NA2 = np.arange(SIZE)

In [12]:
# calculating sum of lists
start = time.time()
result = [(x, y) for x, y in zip(L1, L2)]
print((time.time() - start) * 1000)
# calculating sum of Numpy arrays
start = time.time()
result = NA1 + NA2
print((time.time() - start) * 1000)

112.35904693603516
4.727602005004883


In [20]:
# Finding dimension of numpy array
a = np.array([1, 2, 3])
print(a.ndim)

1


In [21]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b.ndim)

2


In [25]:
# size of each element in array
print(a.itemsize)
# data type of a element in array
print(a.dtype)

8
int64


In [27]:
# size of numpy array
# no. of elements 
print(a.size)
print(b.size)

3
6


In [28]:
# shape of array
# order of matrix
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [31]:
# reshaping -> changing no. of rows and no. of columns
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(a)
print(a.shape)
a = a.reshape(4, 2)
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [33]:
# slicing
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
# printing a specific index
print(a[0, 2])

3


In [35]:
a[0 :, 3]

array([4, 8])