In [4]:
# importing all the necessary packages as required
import seaborn as sns
import pandas as pd
import numpy as np

In [5]:
# loading iris data frame
sns.load_dataset("iris")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
iris = sns.load_dataset("iris")

In [7]:
"""
making x array which contains all the 4 values -> sepal_length	
                                                  sepal_width
                                                  petal_length
                                                  petal_width
"""
x = iris.iloc[:, 0 : 4].values

In [8]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
# making y array which contains the type of flowers
y = iris.iloc[:, 4].values

In [10]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [11]:
# Encoding the string values
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
# since this is supervised learning we are to split data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
# In our whole data 20% is test data and 80% is train data

In [14]:
# Algorithm 1 -> Logistic regression
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
# we have fitted the training model on train_data

LogisticRegression()

In [30]:
# prediction
y_pred = logmodel.predict(x_test)
print(y_pred)
print(y_test)

[0 2 0 1 1 1 0 1 0 0 2 0 0 1 0 0 1 2 0 2 2 2 1 2 2 1 0 2 0 1]
[0 2 0 1 2 1 0 1 0 0 2 0 0 1 0 0 1 2 0 2 2 2 1 2 2 1 0 2 0 1]


In [16]:
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  1,  9]])

In [17]:
# accuracy of model
(12 + 11 + 6) / (12 + 11 + 6 + 1)

0.9666666666666667

In [18]:
# Algorithm 2 -> K nearest neighbours
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
classifier_knn.fit(x_train, y_train)
"""
This algorithm works on distances. It plots the data and check nearest points of a point
After that it decides the majority and gives us output
"""

'\nThis algorithm works on distances. It plots the data and check nearest points of a point\nAfter that it decides the majority and gives us output\n'

In [19]:
# prediction
y_pred = classifier_knn.predict(x_test)
# confusion matrix
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]])

In [20]:
# accuracy of model
(12 + 11 + 6) / (12 + 11 + 6 + 1)

0.9666666666666667

In [21]:
# Algorithm 3 -> Naive Bayes
import sklearn
from sklearn.naive_bayes import GuassianNB
classifier_nb = GuassianNB()
classifier_nb.fit(x_train, y_train)
# prediction
y_pred = classifier_nb.fit(x_train, y_train)
# confusion matrix
confusion_matrix(y_test, y_pred)

ImportError: cannot import name 'GuassianNB' from 'sklearn.naive_bayes' (/config/.local/lib/python3.8/site-packages/sklearn/naive_bayes.py)

In [22]:
# Algorithm 4 -> Support Vector Machine
# sigmoid kernel
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [23]:
# prediction
y_pred = classifier_svm_sigmoid.predict(x_test)
# confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 0, 12,  0],
       [ 0,  8,  0],
       [ 0, 10,  0]])

In [24]:
# accuracy
(8 + 0 + 0) / 30

0.26666666666666666

In [25]:
# linear kernel
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [26]:
# prediction
y_pred = classifier_svm_linear.predict(x_test)
# confusion matrix
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]])

In [27]:
# accuracy
(8 + 9 + 11) / 30

0.9333333333333333

In [28]:
# linear kernel
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [29]:
print("HW")

HW
